##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.10.0-B14] date: [Fri Oct 23 21:36:48 BST 2020] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = app_psu

######################################
# building options
######################################
ENABLE_DEBUG :=no

ENABLE_CLI :=yes

ENABLE_UI :=yes

ENABLE_EEPROM :=yes

ENABLE_VCOM :=yes

ENABLE_UART :=no

ENABLE_SOFT_POWER :=yes

RELEASE :=no

RELEASE_DFU :=no
#######################################
# paths
#######################################
# source path

APP_SRC_DIR :=$(CURDIR)/App
DRIVERS_PATH =$(LIBEMB_PATH)/drv
CMSIS_PATH =$(DRIVERS_PATH)/CMSIS

ifeq ($(shell uname -s), Linux)
REPO_F1 :=STM32Cube_FW_F1_V1.8.0
REPOSITORY :=$(HOME)/STM32Cube/Repository/$(REPO_F1)
else
REPOSITORY :=$(REPO_F1)
endif

FREERTOS_DIR :=$(REPOSITORY)/Middlewares/Third_Party/FreeRTOS/Source

# firmware library path
PERIFLIB_PATH = 

# Build path
BUILD_DIR :=build

BUI_DIR :=./lib/bui

UI_DIR :=./ui

USB_DIR :=./lib/stm32-usb-cdc
######################################
# sources
######################################
# C sources
C_SOURCES =  \
Src/main.c \
Src/stm32f1xx_it.c \
Src/system_stm32f1xx.c \
Src/stm32f1xx_hal_msp.c \
$(APP_SRC_DIR)/components/adcmgr.c \
$(wildcard $(APP_SRC_DIR)/*.c) \
$(LIBEMB_PATH)/src/strfunc.c \
$(DRIVERS_PATH)/gpio/gpio_stm32f1xx.c \
$(DRIVERS_PATH)/dma/dma_stm32f1xx.c \
$(DRIVERS_PATH)/spi/spi_stm32f1xx.c \
$(REPOSITORY)/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c \
$(REPOSITORY)/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c \
$(REPOSITORY)/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c \
$(REPOSITORY)/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc_ex.c \
$(REPOSITORY)/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd.c \
$(REPOSITORY)/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd_ex.c \
$(FREERTOS_DIR)/portable/GCC/ARM_CM3/port.c \
$(FREERTOS_DIR)/portable/MemMang/heap_4.c \
$(FREERTOS_DIR)/list.c \
$(FREERTOS_DIR)/queue.c \
$(FREERTOS_DIR)/tasks.c \
$(FREERTOS_DIR)/timers.c \
$(FREERTOS_DIR)/CMSIS_RTOS/cmsis_os.c \

USB_CDC_SOURCES =\
$(REPOSITORY)/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usb.c \
$(REPOSITORY)/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c \
$(REPOSITORY)/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c \
$(REPOSITORY)/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c \
$(REPOSITORY)/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c \
$(USB_DIR)/usbd_cdc_if.c \
$(USB_DIR)/usbd_desc.c \
$(USB_DIR)/usbd_conf.c \
$(USB_DIR)/usb_device.c

#$(REPOSITORY)/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash.c \
$(REPOSITORY)/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash_ex.c \
$(REPOSITORY)/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c \
$(REPOSITORY)/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio_ex.c \

ifeq ($(filter yes $(ENABLE_EEPROM), $(ENABLE_UI)), yes)
C_SOURCES += \
$(REPOSITORY)/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_i2c.c
endif

ifeq ($(ENABLE_DEBUG),yes)
C_SOURCES +=  \
$(LIBEMB_PATH)/misc/debug.c
endif

ifeq ($(ENABLE_UI),yes)
C_SOURCES +=  \
$(DRIVERS_PATH)/tft/st7735.c \
$(LIBEMB_PATH)/src/liblcd.c \
$(LIBEMB_PATH)/src/button.c \
$(LIBEMB_PATH)/src/font.c \
$(APP_SRC_DIR)/components/pcf8574.c \
$(BUI_DIR)/bui_draw.c
endif

ifeq ($(ENABLE_EEPROM),yes)
C_SOURCES +=  \
$(APP_SRC_DIR)/components/eeprom.c
endif

ifeq ($(ENABLE_VCOM),yes)
C_SOURCES += $(USB_CDC_SOURCES)
endif

# CPP sources
CPP_SOURCES = \
$(wildcard $(APP_SRC_DIR)/*.cpp) \

ifeq ($(ENABLE_CLI),yes)
CPP_SOURCES += \
$(LIBEMB_PATH)/console/console.cpp \
$(wildcard $(APP_SRC_DIR)/console/*.cpp)
endif

ifeq ($(ENABLE_UI),yes)
CPP_SOURCES += \
$(wildcard $(BUI_DIR)/*.cpp) \
$(wildcard $(UI_DIR)/model/*.cpp) \
$(wildcard $(UI_DIR)/common/*.cpp) \
$(wildcard $(UI_DIR)/screen_psu/*.cpp) \
$(wildcard $(UI_DIR)/screen_preset/*.cpp) \
$(wildcard $(UI_DIR)/screen_load/*.cpp) \
$(wildcard $(UI_DIR)/screen_charger/*.cpp)
endif

# ASM sources
ASM_SOURCES =  \
startup/startup_stm32f103xb.s

######################################
# Includes
######################################

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
Inc \
Src \
$(APP_SRC_DIR) \
$(APP_SRC_DIR)/components \
$(APP_SRC_DIR)/console \
$(APP_SRC_DIR)/screen \
$(REPOSITORY)/Drivers/STM32F1xx_HAL_Driver/Inc \
$(REPOSITORY)/Drivers/STM32F1xx_HAL_Driver/Inc/Legacy \
$(REPOSITORY)/Middlewares/ST/STM32_USB_Device_Library/Core/Inc \
$(REPOSITORY)/Drivers/CMSIS/Device/ST/STM32F1xx/Include \
$(REPOSITORY)/Drivers/CMSIS/Include \
$(REPOSITORY)/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc \
$(FREERTOS_DIR)/include \
$(FREERTOS_DIR)/CMSIS_RTOS \
$(FREERTOS_DIR)/portable/GCC/ARM_CM3 \
$(BUI_DIR) \
$(LIBEMB_PATH)/inc \
$(DRIVERS_PATH)/inc \
$(UI_DIR)/model \
$(UI_DIR)/common \
$(UI_DIR)/screen_psu \
$(UI_DIR)/screen_preset \
$(UI_DIR)/screen_charger \
$(UI_DIR)/screen_load \
$(USB_DIR) \

######################################
# firmware library
######################################
PERIFLIB_SOURCES = 

#######################################
# binaries
#######################################
BINPATH = 
PREFIX = arm-none-eabi-
CC = $(BINPATH)$(PREFIX)gcc
CPP = $(BINPATH)$(PREFIX)g++
AS = $(BINPATH)$(PREFIX)gcc -x assembler-with-cpp
CP = $(BINPATH)$(PREFIX)objcopy
AR = $(BINPATH)$(PREFIX)ar
SZ = $(BINPATH)$(PREFIX)size
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU =-mcpu=cortex-m3 -mthumb

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi
#FLOAT-ABI =-u_printf_float

# mcu
MCU = $(CPU) $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
USE_HAL_DRIVER \
STM32F103xB \
USE_ADCMGR

# compile gcc flags
ifeq ($(RELEASE),yes)
OPT =-Os
else ifeq ($(RELEASE_DFU),yes)
OPT =-Os
else
OPT =-Og -g# -gdwarf-2
endif

ifeq ($(ENABLE_DEBUG),yes)
C_DEFS +=ENABLE_DEBUG
endif

ifeq ($(ENABLE_CLI),yes)
C_DEFS +=\
ENABLE_CLI \
CONSOLE_BLOCKING
endif

ifeq ($(ENABLE_UI),yes)
C_DEFS +=\
ENABLE_UI \
USE_COURIER_FONT \
USE_GROTESKBOLD_FONT
endif

ifeq ($(ENABLE_EEPROM),yes)
C_DEFS +=ENABLE_EEPROM
endif

ifeq ($(filter yes $(ENABLE_EEPROM), $(ENABLE_UI)), yes)
C_DEFS +=ENABLE_I2C
endif

ifeq ($(ENABLE_VCOM),yes)
C_DEFS +=ENABLE_USB_CDC
endif

ifeq ($(ENABLE_UART),yes)
C_DEFS +=ENABLE_UART
endif

ifeq ($(ENABLE_SOFT_POWER),yes)
C_DEFS +=ENABLE_SOFT_POWER
endif

ifeq ($(RELEASE),yes)
GIT_TAG :=$(shell git describe --abbrev=0 --tags 2>/dev/null || true)
VERSION :=$(GIT_TAG)#$(GIT_TAG:v=%)
else
VERSION =v0.0.0
endif

ifeq ($(RELEASE_DFU),yes)
C_DEFS +=ENABLE_DFU
LDSCRIPT =startup/f103c8tx_dfu.ld
else
LDSCRIPT =startup/STM32F103C8Tx_FLASH.ld
endif

C_DEFS +=PSU_VERSION=\"$(VERSION)\"

SYMBOLS =$(addprefix -D, $(C_DEFS))
C_INCS =$(addprefix -I, $(C_INCLUDES))

ASFLAGS =$(MCU) $(AS_DEFS) $(AS_INCLUDES) -Wall -fdata-sections -ffunction-sections
CFLAGS =$(MCU) $(OPT) $(C_INCS) $(SYMBOLS) -Wall -fdata-sections -ffunction-sections -std=c11
CPPFLAGS =$(MCU) $(OPT) $(C_INCS) $(SYMBOLS) -Wall -fdata-sections -ffunction-sections -fno-exceptions -fno-unwind-tables -fno-rtti

# Generate dependency information
#CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst))

#######################################
# LDFLAGS
#######################################
# link script

# libraries
#-nostdlib, -nostartfiles: Missign reference to _init
#-specs=nosys.specs, lnosys, not libs: has same size
#-specs=nano.specs: has the small size

LIBS =-specs=nano.specs -nolibc -lstdc++
LIBDIR =-Llib/stm32-usb-cdc
LDFLAGS = $(MCU) -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: elf #$(BUILD_DIR)/$(TARGET).bin #$(BUILD_DIR)/$(TARGET).hex

size: 
	@echo "--- Size ---"
	$(SZ) -A -x $(BUILD_DIR)/$(TARGET).elf
	$(SZ) -B $(BUILD_DIR)/$(TARGET).elf

elf: $(BUILD_DIR)/$(TARGET).elf size

$(TARGET).cfg:
	@echo "Creating opencod configuration file"
	echo "interface jlink" >> $@
	echo "transport select swd" >> $@
	echo "source [find target/stm32f1x.cfg]" >> $@
	echo "adapter_khz 4000" >> $@

#use winusb driver
program: elf $(TARGET).cfg
	openocd -f $(TARGET).cfg -c "program $(BUILD_DIR)/$(TARGET).elf verify reset exit"
#openocd -f $(TARGET).cfg -c "program $(BUILD_DIR)/$(TARGET).bin 0x08001000 verify reset exit"

upload: $(BUILD_DIR)/$(TARGET).bin
	dfu-util -a 0 -s 0x08001000 -D $< -R

test:
#@echo $(CURDIR)
#@echo ""; $(foreach d, $(VPATH), echo $(d);)
#@echo $(filter yes $(ENABLE_EEPROM), $(ENABLE_UI))
	@echo $(SYMBOLS)

lib_cdc:
	$(MAKE) -C $(USB_DIR)

#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
#vpath %.c $(sort $(dir $(C_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(CPP_SOURCES:.cpp=.obj)))
#vpath %.cpp $(sort $(dir $(CPP_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
#vpath %.s $(sort $(dir $(ASM_SOURCES)))

VPATH +=$(dir $(C_SOURCES)) $(dir $(CPP_SOURCES)) $(dir $(ASM_SOURCES))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR)
	@echo "Compiling  " $<
	@$(CC) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/%.obj: %.cpp Makefile | $(BUILD_DIR)
	@echo "Compiling  " $<
	@$(CPP) -c $(CPPFLAGS) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	@echo "Assembling " $<
	@$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) #Makefile
	@echo "--- Linking ---"
	@$(CC) $(OBJECTS) $(LDFLAGS) -o $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir -p $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR .dep $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
#-include $(shell mkdir .dep 2>/dev/null) $(wildcard .dep/*)
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
# *** EOF ***
